name: Build Ubuntu
on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    paths:
      - ".github/workflows/ubuntu.yaml"
      - "linux/ubuntu/**"
  workflow_dispatch:

env:
  SLUG: ghifari160/ubuntu

jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
      with:
        driver: docker-container
    - uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Build Ubuntu
      env:
        ACT: ${{github.event.act}}
      run: |
        ./build.sh \
          --push \
          --from-image ubuntu \
          --from-tag 22.04 \
          --tag "$SLUG:22.04" \
          --tag "$SLUG:jammy" \
          --tag "$SLUG:latest" \
